### ISSUE TITLE
Does not work on encrypted.google.com

### ISSUE THREAD

**Issue by deus0ww** [devunt/make-gis-great-again#5]
Does not work on encrypted.google.com.

**Comment by devunt** [comment]
![image](https://user-images.githubusercontent.com/337728/36323322-df272ffc-1393-11e8-821c-b0fdba3b6465.png)

It works for me. Could you provide more information on it?

**Comment by deus0ww** [comment]
I believe there's a conflict with the "Linkify Plus" userscript (https://arantius.com/misc/greasemonkey/linkify-plus.user.js) but only on encrypted.google.com. On other google domains, the scripts work fine together.

My setup: Mac 10.13.3; Tested with Firefox 58.0.2 and Waterfox 56.0.4; Using the Firefox extension or the Greasemonkey script with ViolentMonkey.

**Comment by devunt** [comment]
Since Linkify Plus userscript's header contains `// @exclude     http*://www.google.tld/search*` entry, it seems safe to assume that developers of the userscript has intended to exclude all of the google search pages. I think they have missed out some exceptional google search domains such as encrypted.google.com, so fixing is needed in their side.

**Comment by deus0ww** [comment]
I have now modified the Linkify Plus header to
// @exclude     http*://*.google.tld/*
to the header.

This fixes it. Thank you for all your help.
